// Complete Business Data for Tyres2Go
export const locations = [
  {
    id: 1,
    name: 'Riccarton (Main)',
    address: '477 Blenheim Road',
    suburb: 'Sockburn',
    city: 'Christchurch',
    postalCode: '8042',
    phone: '03 341 7675',
    email: 'info@tyres2go.net.nz',
    hours: {
      monday: '8:00 AM - 5:00 PM',
      tuesday: '8:00 AM - 5:00 PM',
      wednesday: '8:00 AM - 5:00 PM',
      thursday: '8:00 AM - 5:00 PM',
      friday: '8:00 AM - 5:00 PM',
      saturday: '9:00 AM - 3:00 PM',
      sunday: 'Closed',
    },
    mapUrl: 'https://www.google.com/maps/place/477+Blenheim+Road,+Sockburn,+Christchurch+8042',
    services: ['tyres', 'auto-repairs', 'wof', 'mobile-service'],
    isMain: true,
    status: 'open',
  },
  {
    id: 2,
    name: 'Opawa',
    address: '1/25 Opawa Road',
    suburb: 'Waltham',
    city: 'Christchurch',
    postalCode: '8023',
    phone: '03 374 5034',
    hours: {
      monday: '8:00 AM - 4:00 PM',
      tuesday: '8:00 AM - 4:00 PM',
      wednesday: '8:00 AM - 4:00 PM',
      thursday: '8:00 AM - 4:00 PM',
      friday: '8:00 AM - 4:00 PM',
      saturday: '9:00 AM - 2:00 PM',
      sunday: '9:00 AM - 2:00 PM',
    },
    mapUrl: 'https://www.google.com/maps/place/1/25+Opawa+Road,+Waltham,+Christchurch+8023',
    services: ['tyres'],
    status: 'open',
  },
  {
    id: 3,
    name: 'Sydenham',
    address: '17 Beaumont Street',
    suburb: 'Sydenham',
    city: 'Christchurch',
    postalCode: '8023',
    phone: '03 332 3521',
    hours: {
      monday: '9:00 AM - 5:00 PM',
      tuesday: '9:00 AM - 5:00 PM',
      wednesday: '9:00 AM - 5:00 PM',
      thursday: '9:00 AM - 5:00 PM',
      friday: '9:00 AM - 5:00 PM',
      saturday: '10:00 AM - 3:00 PM',
      sunday: 'Closed',
    },
    mapUrl: 'https://www.google.com/maps/place/17+Beaumont+Street,+Sydenham,+Christchurch+8023',
    services: ['tyres'],
    status: 'open',
  },
  {
    id: 4,
    name: 'New Brighton',
    address: '108 Shortland Street',
    suburb: 'New Brighton',
    city: 'Christchurch',
    postalCode: '8083',
    phone: '03 374 5035',
    hours: {
      monday: '9:00 AM - 5:00 PM',
      tuesday: '9:00 AM - 5:00 PM',
      wednesday: '9:00 AM - 5:00 PM',
      thursday: '9:00 AM - 5:00 PM',
      friday: '9:00 AM - 5:00 PM',
      saturday: 'Closed',
      sunday: 'Closed',
    },
    mapUrl: 'https://www.google.com/maps/place/108+Shortland+Street,+New+Brighton,+Christchurch',
    services: ['tyres'],
    status: 'open',
  },
  {
    id: 5,
    name: 'Shirley',
    address: '7 Shirley Road',
    suburb: 'Shirley',
    city: 'Christchurch',
    postalCode: '8013',
    phone: '03 374 5034',
    hours: {
      monday: '9:00 AM - 5:00 PM',
      tuesday: '9:00 AM - 5:00 PM',
      wednesday: '9:00 AM - 5:00 PM',
      thursday: '9:00 AM - 5:00 PM',
      friday: '9:00 AM - 5:00 PM',
      saturday: '9:00 AM - 3:00 PM',
      sunday: '10:00 AM - 3:00 PM',
    },
    mapUrl: 'https://www.google.com/maps/place/7+Shirley+Road,+Shirley,+Christchurch',
    services: ['tyres'],
    status: 'open',
  },
  {
    id: 6,
    name: 'Rangiora',
    address: '694 Lineside Road',
    suburb: 'Rangiora',
    city: 'Rangiora',
    postalCode: '7400',
    phone: '03 327 7140',
    hours: {
      monday: '9:00 AM - 5:00 PM',
      tuesday: '9:00 AM - 5:00 PM',
      wednesday: '9:00 AM - 5:00 PM',
      thursday: '9:00 AM - 5:00 PM',
      friday: '9:00 AM - 5:00 PM',
      saturday: '9:00 AM - 3:00 PM',
      sunday: 'Closed',
    },
    mapUrl: 'https://www.google.com/maps/place/694+Lineside+Road,+Rangiora+7400',
    services: ['tyres'],
    status: 'open',
  },
];

export const tyreServices = [
  {
    id: 1,
    name: 'Passenger Tyres',
    description: 'Quality tyres for your family car from trusted brands',
    icon: 'Car',
    slug: 'passenger-tyres',
  },
  {
    id: 2,
    name: '4WD/SUV Tyres',
    description: 'Robust tyres for your 4WD and SUV vehicles',
    icon: 'Truck',
    slug: '4wd-suv-tyres',
  },
  {
    id: 3,
    name: 'High Performance Tyres',
    description: 'Premium tyres for enhanced performance and handling',
    icon: 'Zap',
    slug: 'high-performance-tyres',
  },
  {
    id: 4,
    name: 'Van / Light Truck Tyres',
    description: 'Durable tyres for commercial vehicles',
    icon: 'TruckIcon',
    slug: 'van-light-truck-tyres',
  },
  {
    id: 5,
    name: 'Fuel Efficient Tyres',
    description: 'Eco-friendly tyres that save you money on fuel',
    icon: 'Leaf',
    slug: 'fuel-efficient-tyres',
  },
  {
    id: 6,
    name: 'Run Flat Tyres',
    description: 'Safety tyres that keep you moving after a puncture',
    icon: 'Shield',
    slug: 'run-flat-tyres',
  },
  {
    id: 7,
    name: 'Wheel Alignment',
    description: 'Precise wheel alignment for optimal tyre performance',
    icon: 'Settings',
    slug: 'wheel-alignment',
  },
  {
    id: 8,
    name: 'Wheel Balancing',
    description: 'Professional balancing for a smooth ride',
    icon: 'Activity',
    slug: 'wheel-balancing',
  },
  {
    id: 9,
    name: 'Puncture Repairs',
    description: 'Quick and reliable puncture repair services',
    icon: 'Wrench',
    slug: 'puncture-repairs',
  },
  {
    id: 10,
    name: 'Tyre Rotation',
    description: 'Extend tyre life with regular rotation',
    icon: 'RefreshCw',
    slug: 'tyre-rotation',
  },
  {
    id: 11,
    name: 'Nitrogen Inflation',
    description: 'Enhance tyre performance with nitrogen filling',
    icon: 'Wind',
    slug: 'nitrogen-inflation',
  },
  {
    id: 12,
    name: 'Mobile Tyre Service',
    description: 'We come to you - home, office, anywhere in Christchurch',
    icon: 'MapPin',
    slug: 'mobile-service',
  },
];

export const autoServices = [
  {
    id: 1,
    name: 'WOF Inspections',
    description: 'Warrant of Fitness inspections and repairs',
    icon: 'ClipboardCheck',
    category: 'servicing',
  },
  {
    id: 2,
    name: 'Car/Vehicle Service',
    description: 'Comprehensive vehicle servicing for all makes and models',
    icon: 'Wrench',
    category: 'servicing',
  },
  {
    id: 3,
    name: 'Oil Change',
    description: 'Regular oil changes to keep your engine running smoothly',
    icon: 'Droplet',
    category: 'servicing',
  },
  {
    id: 4,
    name: 'Filtration Service',
    description: 'Air, oil, and fuel filter replacements',
    icon: 'Filter',
    category: 'servicing',
  },
  {
    id: 5,
    name: 'Brake Repairs',
    description: 'Expert brake repairs for your safety',
    icon: 'Disc',
    category: 'repairs',
  },
  {
    id: 6,
    name: 'Transmission Repairs',
    description: 'Professional transmission servicing and repairs',
    icon: 'Cog',
    category: 'repairs',
  },
  {
    id: 7,
    name: 'Engine Repairs',
    description: 'Complete engine diagnostics and repairs',
    icon: 'Cpu',
    category: 'repairs',
  },
  {
    id: 8,
    name: 'Exhaust & Mufflers',
    description: 'Exhaust system repairs and replacements',
    icon: 'Wind',
    category: 'repairs',
  },
  {
    id: 9,
    name: 'Lighting Repair',
    description: 'Headlight, taillight, and indicator repairs',
    icon: 'Lightbulb',
    category: 'electrical',
  },
  {
    id: 10,
    name: 'Auto Electrical',
    description: 'Complete auto electrical diagnostics and repairs',
    icon: 'Zap',
    category: 'electrical',
  },
  {
    id: 11,
    name: 'Sound System',
    description: 'Car audio system installation and repairs',
    icon: 'Speaker',
    category: 'electrical',
  },
  {
    id: 12,
    name: 'Alarm & Wiring',
    description: 'Security system and wiring services',
    icon: 'Bell',
    category: 'electrical',
  },
  {
    id: 13,
    name: 'Dash Warning Lights',
    description: 'Diagnostic services for warning lights',
    icon: 'AlertTriangle',
    category: 'electrical',
  },
  {
    id: 14,
    name: 'Batteries',
    description: 'Battery testing and replacement',
    icon: 'Battery',
    category: 'servicing',
  },
  {
    id: 15,
    name: 'Suspensions',
    description: 'Suspension repairs and replacements',
    icon: 'Minus',
    category: 'repairs',
  },
];

export const tyreBrands = [
  'Michelin', 'Bridgestone', 'Continental', 'Dunlop', 'Goodyear',
  'Pirelli', 'Firestone', 'BFGoodrich', 'Hankook', 'Kumho',
  'Toyo', 'Yokohama', 'Nankang', 'Maxxis', 'Triangle',
  'Goodride', 'Haida', 'Kapsen', 'Laufenn', 'MarkMa',
  'Royal Black', 'Supercat', 'Zeta', 'Achilles', 'Altenzo',
];

export const testimonials = [
  {
    id: 1,
    name: 'Grant Wilson',
    text: "Can't say enough about these guys. Found a fault in my Torana that was causing issues for ages among other things. Car runs like a dream now. Stoked to have it running mint for the summer season. Highly recommended JT for all your motoring needs. Thanks Deno and Mike. Legends. 👍",
    rating: 5,
    service: 'Auto Repairs',
  },
  {
    id: 2,
    name: 'Spencer Brown',
    text: 'Have been using Dean for over 10 Years now. Fantastic mechanic and straight to the point. Very well priced as well. Highly recommend!!!',
    rating: 5,
    service: 'Vehicle Service',
  },
  {
    id: 3,
    name: 'Anatoly Litovsky',
    text: 'Went in for WOF and tune up on 73 ford, left with car running mint.',
    rating: 5,
    service: 'WOF & Tune Up',
  },
  {
    id: 4,
    name: 'Nick Jenness',
    text: 'Awesome people',
    rating: 5,
    service: 'General Service',
  },
  {
    id: 5,
    name: 'Shaun McLaren',
    text: 'Great service and very good price 😃',
    rating: 5,
    service: 'Tyre Service',
  },
  {
    id: 6,
    name: 'J Gray',
    text: 'JT Automotive were very professional and fitted my car in when no other WOF company could. Top rate service that I highly recommend.',
    rating: 5,
    service: 'WOF',
  },
];

export const faqs = [
  {
    id: 1,
    question: 'How do I find the right tyre for my car?',
    answer: 'Choosing the right tyres is vital for your driving experience and road safety. Stick to the tyre sizes recommended for your car, pick the right tread pattern ideal for your driving conditions, and ensure high quality rubber compound for better longevity. Go for a trustworthy brand offering the best warranty. Our expert team can help you choose the perfect tyre for your needs.',
  },
  {
    id: 2,
    question: 'What is the minimum legal tread depth?',
    answer: 'In New Zealand, the minimum legal tread depth is 1.5mm across the full width of the tread. However, we recommend replacing tyres when tread depth reaches 3mm for optimal safety and performance, especially in wet conditions.',
  },
  {
    id: 3,
    question: 'How will I know when to replace my car\'s tyres?',
    answer: 'Replace your tyres when the tread depth is below 3mm, if there are visible cracks or bulges, uneven wear patterns, or if the tyre is more than 6 years old regardless of tread depth. Our technicians can inspect your tyres and provide expert advice.',
  },
  {
    id: 4,
    question: 'Can I check the tread depth of the tyres?',
    answer: 'Yes! Use the 20-cent coin test - insert a 20-cent coin into the tread groove. If you can see the top of the band around the edge of the coin, your tread is too low. You can also visit any of our 6 locations for a free tyre inspection.',
  },
  {
    id: 5,
    question: 'How often should I get a safety check for my vehicle?',
    answer: 'We recommend a comprehensive safety check every 6 months or 10,000km, whichever comes first. For vehicles requiring a WOF, annual inspections are mandatory. Regular checks help identify potential issues before they become serious problems.',
  },
  {
    id: 6,
    question: 'What does a standard vehicle service include?',
    answer: 'Our standard service includes oil and filter change, brake inspection, tyre rotation and pressure check, fluid level checks, battery test, lights and wiper inspection, and a comprehensive safety check. We provide a detailed report of our findings.',
  },
  {
    id: 7,
    question: 'Do you service all types of vehicles?',
    answer: 'Yes! We service all makes and models including passenger cars, 4WDs, SUVs, vans, light trucks, motorhomes, and commercial vehicles. Our experienced technicians are equipped to handle European, Japanese, American, and Korean vehicles.',
  },
  {
    id: 8,
    question: 'What is a Warrant of Fitness (WoF) and why do I need it?',
    answer: 'A WOF is a regular safety check required by law in New Zealand. Vehicles must pass a WOF inspection to ensure they meet minimum safety standards. Most passenger vehicles need a WOF annually, while newer vehicles (first registered after January 2000) need one at 3 years old, then annually.',
  },
  {
    id: 9,
    question: 'Do you provide mobile tyre services?',
    answer: 'Yes! Our Mobile Tyre Service covers all of Christchurch 7 days a week. We come to your home, office, or anywhere you need us. Our mobile vans are equipped with state-of-the-art fitting and balancing machines. Call 03 341 7675 to book.',
  },
  {
    id: 10,
    question: 'Do you offer payment options?',
    answer: 'Yes, we accept cash, EFTPOS, all major credit cards, and offer various payment plans to suit your budget. Ask our team about our flexible payment options when you visit or call us.',
  },
];

export const businessStats = {
  yearsExperience: '15+',
  locations: 6,
  brandsAvailable: '25+',
  googleRating: 4.1,
  mtaCertified: true,
  servicesProvided: 25,
};

export default {
  locations,
  tyreServices,
  autoServices,
  tyreBrands,
  testimonials,
  faqs,
  businessStats,
};
