// Complete Business Data for Tyres2Go
export const locations = [
  {
    id: 1,
    name: 'Riccarton (Main)',
    address: '477 Blenheim Road',
    suburb: 'Sockburn',
    city: 'Christchurch',
    postalCode: '8042',
    phone: '03 341 7675',
    email: 'info@tyres2go.net.nz',
    hours: {
      monday: '8:00 AM - 5:00 PM',
      tuesday: '8:00 AM - 5:00 PM',
      wednesday: '8:00 AM - 5:00 PM',
      thursday: '8:00 AM - 5:00 PM',
      friday: '8:00 AM - 5:00 PM',
      saturday: '9:00 AM - 3:00 PM',
      sunday: 'Closed',
    },
    mapUrl: 'https://www.google.com/maps/place/477+Blenheim+Road,+Sockburn,+Christchurch+8042',
    services: ['tyres', 'auto-repairs', 'wof', 'mobile-service'],
    isMain: true,
    status: 'open',
  },
  {
    id: 2,
    name: 'Opawa',
    address: '1/25 Opawa Road',
    suburb: 'Waltham',
    city: 'Christchurch',
    postalCode: '8023',
    phone: '03 374 5034',
    hours: {
      monday: '8:00 AM - 4:00 PM',
      tuesday: '8:00 AM - 4:00 PM',
      wednesday: '8:00 AM - 4:00 PM',
      thursday: '8:00 AM - 4:00 PM',
      friday: '8:00 AM - 4:00 PM',
      saturday: '9:00 AM - 2:00 PM',
      sunday: '9:00 AM - 2:00 PM',
    },
    mapUrl: 'https://www.google.com/maps/place/1/25+Opawa+Road,+Waltham,+Christchurch+8023',
    services: ['tyres'],
    status: 'open',
  },
  {
    id: 3,
    name: 'Sydenham',
    address: '17 Beaumont Street',
    suburb: 'Sydenham',
    city: 'Christchurch',
    postalCode: '8023',
    phone: '03 332 3521',
    hours: {
      monday: '9:00 AM - 5:00 PM',
      tuesday: '9:00 AM - 5:00 PM',
      wednesday: '9:00 AM - 5:00 PM',
      thursday: '9:00 AM - 5:00 PM',
      friday: '9:00 AM - 5:00 PM',
      saturday: '10:00 AM - 3:00 PM',
      sunday: 'Closed',
    },
    mapUrl: 'https://www.google.com/maps/place/17+Beaumont+Street,+Sydenham,+Christchurch+8023',
    services: ['tyres'],
    status: 'open',
  },
  {
    id: 4,
    name: 'New Brighton',
    address: '108 Shortland Street',
    suburb: 'New Brighton',
    city: 'Christchurch',
    postalCode: '8083',
    phone: '03 374 5035',
    hours: {
      monday: '9:00 AM - 5:00 PM',
      tuesday: '9:00 AM - 5:00 PM',
      wednesday: '9:00 AM - 5:00 PM',
      thursday: '9:00 AM - 5:00 PM',
      friday: '9:00 AM - 5:00 PM',
      saturday: 'Closed',
      sunday: 'Closed',
    },
    mapUrl: 'https://www.google.com/maps/place/108+Shortland+Street,+New+Brighton,+Christchurch',
    services: ['tyres'],
    status: 'open',
  },
  {
    id: 5,
    name: 'Shirley',
    address: '7 Shirley Road',
    suburb: 'Shirley',
    city: 'Christchurch',
    postalCode: '8013',
    phone: '03 374 5034',
    hours: {
      monday: '9:00 AM - 5:00 PM',
      tuesday: '9:00 AM - 5:00 PM',
      wednesday: '9:00 AM - 5:00 PM',
      thursday: '9:00 AM - 5:00 PM',
      friday: '9:00 AM - 5:00 PM',
      saturday: '9:00 AM - 3:00 PM',
      sunday: '10:00 AM - 3:00 PM',
    },
    mapUrl: 'https://www.google.com/maps/place/7+Shirley+Road,+Shirley,+Christchurch',
    services: ['tyres'],
    status: 'open',
  },
  {
    id: 6,
    name: 'Rangiora',
    address: '694 Lineside Road',
    suburb: 'Rangiora',
    city: 'Rangiora',
    postalCode: '7400',
    phone: '03 327 7140',
    hours: {
      monday: '9:00 AM - 5:00 PM',
      tuesday: '9:00 AM - 5:00 PM',
      wednesday: '9:00 AM - 5:00 PM',
      thursday: '9:00 AM - 5:00 PM',
      friday: '9:00 AM - 5:00 PM',
      saturday: '9:00 AM - 3:00 PM',
      sunday: 'Closed',
    },
    mapUrl: 'https://www.google.com/maps/place/694+Lineside+Road,+Rangiora+7400',
    services: ['tyres'],
    status: 'open',
  },
];

export const tyreServices = [
  {
    id: 1,
    name: 'Passenger Tyres',
    description: 'Quality tyres for your family car from trusted brands',
    icon: 'Car',
    slug: 'passenger-tyres',
  },
  {
    id: 2,
    name: '4WD/SUV Tyres',
    description: 'Robust tyres for your 4WD and SUV vehicles',
    icon: 'Truck',
    slug: '4wd-suv-tyres',
  },
  {
    id: 3,
    name: 'High Performance Tyres',
    description: 'Premium tyres for enhanced performance and handling',
    icon: 'Zap',
    slug: 'high-performance-tyres',
  },
  {
    id: 4,
    name: 'Van / Light Truck Tyres',
    description: 'Durable tyres for commercial vehicles',
    icon: 'TruckIcon',
    slug: 'van-light-truck-tyres',
  },
  {
    id: 5,
    name: 'Fuel Efficient Tyres',
    description: 'Eco-friendly tyres that save you money on fuel',
    icon: 'Leaf',
    slug: 'fuel-efficient-tyres',
  },
  {
    id: 6,
    name: 'Run Flat Tyres',
    description: 'Safety tyres that keep you moving after a puncture',
    icon: 'Shield',
    slug: 'run-flat-tyres',
  },
  {
    id: 7,
    name: 'Wheel Alignment',
    description: 'Precise wheel alignment for optimal tyre performance',
    icon: 'Settings',
    slug: 'wheel-alignment',
  },
  {
    id: 8,
    name: 'Wheel Balancing',
    description: 'Professional balancing for a smooth ride',
    icon: 'Activity',
    slug: 'wheel-balancing',
  },
  {
    id: 9,
    name: 'Puncture Repairs',
    description: 'Quick and reliable puncture repair services',
    icon: 'Wrench',
    slug: 'puncture-repairs',
  },
  {
    id: 10,
    name: 'Tyre Rotation',
    description: 'Extend tyre life with regular rotation',
    icon: 'RefreshCw',
    slug: 'tyre-rotation',
  },
  {
    id: 11,
    name: 'Nitrogen Inflation',
    description: 'Enhance tyre performance with nitrogen filling',
    icon: 'Wind',
    slug: 'nitrogen-inflation',
  },
  {
    id: 12,
    name: 'Mobile Tyre Service',
    description: 'We come to you - home, office, anywhere in Christchurch',
    icon: 'MapPin',
    slug: 'mobile-service',
  },
];

export const autoServices = [
  {
    id: 1,
    name: 'WOF Inspections',
    description: 'Comprehensive Warrant of Fitness inspections to ensure your vehicle meets safety standards. MTA certified service.',
    icon: 'ClipboardCheck',
    category: 'servicing',
    slug: 'wof-inspections',
  },
  {
    id: 2,
    name: 'General Vehicle Servicing',
    description: 'Complete vehicle servicing including oil change, filter replacement, and multi-point safety inspection.',
    icon: 'Wrench',
    category: 'servicing',
    slug: 'vehicle-servicing',
  },
  {
    id: 3,
    name: 'Oil & Filtration Services',
    description: 'Regular oil changes and filter replacements using quality oils suitable for your vehicle.',
    icon: 'Droplet',
    category: 'servicing',
    slug: 'oil-filtration',
  },
  {
    id: 4,
    name: 'Transmission Service',
    description: 'Automatic, CVT, and manual transmission servicing to ensure smooth gear changes.',
    icon: 'Cog',
    category: 'servicing',
    slug: 'transmission-service',
  },
  {
    id: 5,
    name: 'Differential & Transfer Case',
    description: 'Front/rear differential and transfer case service for 4WD and SUV vehicles.',
    icon: 'Settings',
    category: 'servicing',
    slug: 'differential-service',
  },
  {
    id: 6,
    name: 'Engine Flush',
    description: 'Professional engine flush to remove sludge and improve engine performance.',
    icon: 'Cpu',
    category: 'servicing',
    slug: 'engine-flush',
  },
  {
    id: 7,
    name: 'Power Steering Flush',
    description: 'Power steering fluid replacement for smooth steering operation.',
    icon: 'Disc',
    category: 'servicing',
    slug: 'power-steering-flush',
  },
  {
    id: 8,
    name: 'Radiator Coolant Exchange',
    description: 'Coolant system flush and refill to prevent overheating and corrosion.',
    icon: 'Thermometer',
    category: 'servicing',
    slug: 'coolant-exchange',
  },
  {
    id: 9,
    name: 'Diesel Fuel Filters',
    description: 'Diesel fuel filter replacement to maintain optimal engine performance.',
    icon: 'Filter',
    category: 'servicing',
    slug: 'diesel-fuel-filters',
  },
  {
    id: 10,
    name: 'Pre-Purchase Inspections',
    description: 'Comprehensive vehicle inspection before you buy to identify potential issues.',
    icon: 'ClipboardCheck',
    category: 'servicing',
    slug: 'pre-purchase-inspection',
  },
  {
    id: 11,
    name: 'Brake Repairs',
    description: 'Complete brake system inspection, pad replacement, disc machining, and repairs for optimal safety.',
    icon: 'Disc',
    category: 'repairs',
    slug: 'brake-repairs',
  },
  {
    id: 12,
    name: 'Transmission Repairs',
    description: 'Expert transmission diagnostics and repairs for all types of transmissions.',
    icon: 'Cog',
    category: 'repairs',
    slug: 'transmission-repairs',
  },
  {
    id: 13,
    name: 'Engine Repairs',
    description: 'Advanced engine diagnostics and repairs to restore your vehicle\'s performance.',
    icon: 'Cpu',
    category: 'repairs',
    slug: 'engine-repairs',
  },
  {
    id: 14,
    name: 'Radiator & Cooling',
    description: 'Radiator repairs, replacements, and cooling system maintenance.',
    icon: 'Thermometer',
    category: 'repairs',
    slug: 'radiator-cooling',
  },
  {
    id: 15,
    name: 'Exhaust & Muffler',
    description: 'Exhaust system repairs, muffler replacements, and emission testing.',
    icon: 'Wind',
    category: 'repairs',
    slug: 'exhaust-muffler',
  },
  {
    id: 16,
    name: 'Suspension & Steering',
    description: 'Suspension repairs, shock absorber replacement, and steering system maintenance.',
    icon: 'Minus',
    category: 'repairs',
    slug: 'suspension-steering',
  },
  {
    id: 17,
    name: 'Heating & Air Conditioning',
    description: 'Air conditioning repairs, re-gassing, and heating system maintenance.',
    icon: 'Wind',
    category: 'repairs',
    slug: 'heating-air-conditioning',
  },
  {
    id: 18,
    name: 'Air Conditioning Repair',
    description: 'Complete air conditioning diagnostics, repairs, and re-gassing services.',
    icon: 'Wind',
    category: 'electrical',
    slug: 'air-conditioning-repair',
  },
  {
    id: 19,
    name: 'Lighting Repair',
    description: 'Headlight, taillight, indicator, and interior lighting repairs and replacements.',
    icon: 'Lightbulb',
    category: 'electrical',
    slug: 'lighting-repair',
  },
  {
    id: 20,
    name: 'Auto Electrical Repairs',
    description: 'Complete auto electrical diagnostics, wiring repairs, and electrical system maintenance.',
    icon: 'Zap',
    category: 'electrical',
    slug: 'auto-electrical',
  },
  {
    id: 21,
    name: 'Sound System & Alarm',
    description: 'Car audio system installation, repairs, and security alarm systems.',
    icon: 'Speaker',
    category: 'electrical',
    slug: 'sound-system-alarm',
  },
  {
    id: 22,
    name: 'Dash Warning Lights',
    description: 'Diagnostic services for dashboard warning lights and fault code reading.',
    icon: 'AlertTriangle',
    category: 'electrical',
    slug: 'dash-warning-lights',
  },
  {
    id: 23,
    name: 'Batteries',
    description: 'Battery testing, replacement, and charging system diagnostics.',
    icon: 'Battery',
    category: 'servicing',
    slug: 'batteries',
  },
  {
    id: 24,
    name: 'Hybrid & Electric Services',
    description: 'Specialized servicing for hybrid and electric vehicles.',
    icon: 'Zap',
    category: 'servicing',
    slug: 'hybrid-electric-services',
  },
];

export const tyreBrands = [
  'Michelin', 'Bridgestone', 'Continental', 'Dunlop', 'Goodyear',
  'Pirelli', 'Firestone', 'BFGoodrich', 'Hankook', 'Kumho',
  'Toyo', 'Yokohama', 'Nankang', 'Maxxis', 'Triangle',
  'Goodride', 'Haida', 'Kapsen', 'Laufenn', 'MarkMa',
  'Royal Black', 'Supercat', 'Zeta', 'Achilles', 'Altenzo',
];

export const testimonials = [
  {
    id: 1,
    name: 'Grant Wilson',
    text: "Can't say enough about these guys. Found a fault in my Torana that was causing issues for ages among other things. Car runs like a dream now. Stoked to have it running mint for the summer season. Highly recommended JT for all your motoring needs. Thanks Deno and Mike. Legends. 👍",
    rating: 5,
    service: 'Auto Repairs',
  },
  {
    id: 2,
    name: 'Spencer Brown',
    text: 'Have been using Dean for over 10 Years now. Fantastic mechanic and straight to the point. Very well priced as well. Highly recommend!!!',
    rating: 5,
    service: 'Vehicle Service',
  },
  {
    id: 3,
    name: 'Anatoly Litovsky',
    text: 'Went in for WOF and tune up on 73 ford, left with car running mint.',
    rating: 5,
    service: 'WOF & Tune Up',
  },
  {
    id: 4,
    name: 'Nick Jenness',
    text: 'Awesome people',
    rating: 5,
    service: 'General Service',
  },
  {
    id: 5,
    name: 'Shaun McLaren',
    text: 'Great service and very good price 😃',
    rating: 5,
    service: 'Tyre Service',
  },
  {
    id: 6,
    name: 'J Gray',
    text: 'JT Automotive were very professional and fitted my car in when no other WOF company could. Top rate service that I highly recommend.',
    rating: 5,
    service: 'WOF',
  },
];

export const faqs = [
  {
    id: 1,
    question: 'How do I find the right tyre for my car?',
    answer: 'Choosing the right tyres is vital for your driving experience and road safety. Stick to the tyre sizes recommended for your car, pick the right tread pattern ideal for your driving conditions, and ensure high quality rubber compound for better longevity. Go for a trustworthy brand offering the best warranty. Our expert team can help you choose the perfect tyre for your needs.',
  },
  {
    id: 2,
    question: 'What is the minimum legal tread depth?',
    answer: 'In New Zealand, the minimum legal tread depth is 1.5mm across the full width of the tread. However, we recommend replacing tyres when tread depth reaches 3mm for optimal safety and performance, especially in wet conditions.',
  },
  {
    id: 3,
    question: 'How will I know when to replace my car\'s tyres?',
    answer: 'Replace your tyres when the tread depth is below 3mm, if there are visible cracks or bulges, uneven wear patterns, or if the tyre is more than 6 years old regardless of tread depth. Our technicians can inspect your tyres and provide expert advice.',
  },
  {
    id: 4,
    question: 'Can I check the tread depth of the tyres?',
    answer: 'Yes! Use the 20-cent coin test - insert a 20-cent coin into the tread groove. If you can see the top of the band around the edge of the coin, your tread is too low. You can also visit any of our 6 locations for a free tyre inspection.',
  },
  {
    id: 5,
    question: 'How often should I get a safety check for my vehicle?',
    answer: 'We recommend a comprehensive safety check every 6 months or 10,000km, whichever comes first. For vehicles requiring a WOF, annual inspections are mandatory. Regular checks help identify potential issues before they become serious problems.',
  },
  {
    id: 6,
    question: 'What does a standard vehicle service include?',
    answer: 'Our standard service includes oil and filter change, brake inspection, tyre rotation and pressure check, fluid level checks, battery test, lights and wiper inspection, and a comprehensive safety check. We provide a detailed report of our findings.',
  },
  {
    id: 7,
    question: 'Do you service all types of vehicles?',
    answer: 'Yes! We service all makes and models including passenger cars, 4WDs, SUVs, vans, light trucks, motorhomes, and commercial vehicles. Our experienced technicians are equipped to handle European, Japanese, American, and Korean vehicles.',
  },
  {
    id: 8,
    question: 'What is a Warrant of Fitness (WoF) and why do I need it?',
    answer: 'A WOF is a regular safety check required by law in New Zealand. Vehicles must pass a WOF inspection to ensure they meet minimum safety standards. Most passenger vehicles need a WOF annually, while newer vehicles (first registered after January 2000) need one at 3 years old, then annually.',
  },
  {
    id: 9,
    question: 'Do you provide mobile tyre services?',
    answer: 'Yes! Our Mobile Tyre Service covers all of Christchurch 7 days a week. We come to your home, office, or anywhere you need us. Our mobile vans are equipped with state-of-the-art fitting and balancing machines. Call 03 341 7675 to book.',
  },
  {
    id: 10,
    question: 'Do you offer payment options?',
    answer: 'Yes, we accept cash, EFTPOS, all major credit cards, and offer various payment plans to suit your budget. Ask our team about our flexible payment options when you visit or call us.',
  },
];

export const businessStats = {
  yearsExperience: '15+',
  locations: 6,
  brandsAvailable: '25+',
  googleRating: 4.1,
  mtaCertified: true,
  servicesProvided: 25,
};

// When to Replace Your Tyres - Guidance from Tyres2Go
export const tyreReplacementGuidance = {
  title: 'When Should You Replace Your Tyres?',
  intro: 'Your tyres are critical to your vehicle\'s safety and performance. Regular checks and timely replacement ensure optimal grip, handling, and safety on New Zealand roads.',
  signs: [
    {
      id: 1,
      title: 'Low Tread Depth',
      description: 'When tread depth falls below 1.5mm (the legal minimum in NZ is 1.5mm), it\'s time for replacement. We recommend replacing at 3mm for optimal safety, especially in wet conditions.',
      icon: 'Gauge',
    },
    {
      id: 2,
      title: 'Poor Grip in Wet Conditions',
      description: 'If you notice reduced traction, longer braking distances, or sliding on wet roads, your tyres may be worn and need replacement.',
      icon: 'Droplet',
    },
    {
      id: 3,
      title: 'High Mileage',
      description: 'Most tyres last between 40,000-80,000 km depending on driving habits and conditions. Regular rotation can extend tyre life.',
      icon: 'Navigation',
    },
    {
      id: 4,
      title: 'Trouble Driving Straight',
      description: 'Vehicle pulling to one side may indicate uneven tyre wear or alignment issues. A wheel alignment check and tyre inspection are recommended.',
      icon: 'AlertTriangle',
    },
    {
      id: 5,
      title: 'Frequent Punctures',
      description: 'Repeated punctures may indicate tyre damage or deterioration. Inspection by our technicians can determine if replacement is necessary.',
      icon: 'Tool',
    },
    {
      id: 6,
      title: 'Visible Damage',
      description: 'Cracks, bulges, cuts, or exposed cords are serious safety concerns requiring immediate replacement.',
      icon: 'XCircle',
    },
  ],
};

// Detailed Service Information
export const serviceDetails = {
  wheelAlignment: {
    title: 'Wheel Alignment Service',
    description: 'Precision wheel alignment using Hunter laser technology to improve handling, reduce tyre wear, and enhance fuel efficiency.',
    benefits: [
      'Extends tyre life by preventing uneven wear',
      'Improves vehicle handling and safety',
      'Reduces fuel consumption',
      'Provides a smoother, more comfortable ride',
    ],
    equipment: 'We use 9 Hunter Laser wheel alignment machines across our locations - the most advanced alignment technology available.',
  },
  punctureRepair: {
    title: 'Puncture Repair Service',
    description: 'Quick and reliable puncture repairs to get you back on the road safely.',
    benefits: [
      'Fast turnaround - most repairs completed within 30 minutes',
      'Professional plug or patch repairs',
      'Thorough inspection to ensure repairability',
      'Warranty on all repairs',
    ],
  },
  tyreRotation: {
    title: 'Tyre Rotation',
    description: 'Regular tyre rotation helps ensure even wear across all tyres, extending their lifespan.',
    benefits: [
      'Extends tyre life by 20-30%',
      'Ensures even tread wear',
      'Maintains optimal handling',
      'Cost-effective maintenance',
    ],
    recommendation: 'We recommend rotating tyres every 10,000 km or 6 months.',
  },
  nitrogenInflation: {
    title: 'Nitrogen Tyre Inflation',
    description: 'Inflate your tyres with nitrogen for improved performance and longevity.',
    benefits: [
      'Maintains tyre pressure longer than regular air',
      'Reduces oxidation and extends tyre life',
      'Improves fuel efficiency',
      'Better pressure retention in temperature changes',
    ],
  },
  mobileTyreService: {
    title: 'Mobile Tyre Service',
    description: 'Convenient mobile tyre fitting and balancing at your location across Christchurch and Canterbury.',
    benefits: [
      'We come to your home, office, or anywhere in Christchurch',
      'Available 7 days a week',
      'Fully equipped mobile vans with fitting and balancing machines',
      'Same quality service as our workshops',
    ],
    coverage: 'Christchurch metro, Rangiora, Kaiapoi, and surrounding areas',
  },
};

// Company Values and Why Choose Us
export const companyValues = {
  tyres2go: {
    title: 'About Tyres2Go',
    description: 'Tyres2Go is your local, MTA-certified tyre service centre delivering top-notch services and safety to Christchurch drivers. We are passionate about quality and customer satisfaction.',
    values: [
      {
        title: 'Customer-Centric Service',
        description: 'Your satisfaction is our priority. We listen to your needs and provide personalized solutions.',
      },
      {
        title: 'Quality Assurance',
        description: 'We only stock quality tyre brands and use state-of-the-art equipment for all services.',
      },
      {
        title: 'State-of-the-Art Equipment',
        description: '9 Hunter Laser wheel alignment machines and modern tyre fitting equipment across all locations.',
      },
      {
        title: 'Comprehensive Services',
        description: 'From tyres to batteries, wheels to suspensions - we\'re your one-stop automotive shop.',
      },
      {
        title: 'Transparent Communication',
        description: 'Clear explanations, honest advice, and no hidden fees. We keep you informed every step.',
      },
    ],
    certifications: ['MTA Member', 'Hunter Alignment Certified'],
  },
  jtAuto: {
    title: 'About JT Automotive',
    description: 'JT Automotive offers comprehensive car repairs and prompt WOF service at our Riccarton garage. We serve private car owners and commercial fleets with experienced mechanics and modern facilities.',
    values: [
      {
        title: 'Qualified Mechanics',
        description: 'All our technicians are fully qualified and experienced in servicing all makes and models.',
      },
      {
        title: 'Spacious Facilities',
        description: 'Large workshop equipped for WOFs, servicing, and all mechanical and auto-electrical repairs.',
      },
      {
        title: 'Prompt Turnaround',
        description: 'We understand your time is valuable. Most services completed same day or next day.',
      },
      {
        title: 'Pick-up/Drop-off Service',
        description: 'Convenient pick-up and drop-off service available for customers in Christchurch.',
      },
      {
        title: 'Courtesy Cars',
        description: 'Courtesy vehicles available while your car is being serviced (subject to availability).',
      },
      {
        title: 'MTA Membership',
        description: 'Member of the Motor Trade Association with Dealer Warranty protection.',
      },
      {
        title: 'Six-Day Availability',
        description: 'Open Monday-Friday 8am-5pm and Saturday 9am-3pm for your convenience.',
      },
    ],
    safetyAdvice: 'We recommend a comprehensive safety check every 6 months. While a WOF is required annually, it may miss gradual issues like tyre wear, brake deterioration, or fluid leaks that develop between inspections.',
  },
  combined: {
    title: 'Why Choose Tyres2Go & JT Automotive',
    description: 'When you choose us, you get the best of both worlds - expert tyre services from Tyres2Go and comprehensive automotive repairs from JT Automotive, all under one trusted brand.',
    reasons: [
      'Over 15 years of combined experience in Christchurch',
      '6 convenient locations across Christchurch and Canterbury',
      'MTA certified with industry-leading standards',
      '25+ quality tyre brands available',
      'State-of-the-art equipment including 9 Hunter Laser alignment machines',
      'Comprehensive services - tyres, mechanical, electrical, WOF',
      'Mobile tyre service 7 days a week',
      'Qualified and experienced technicians',
      'Transparent pricing with no hidden fees',
      'Free quotes and honest advice',
      'Prompt turnaround times',
      'Courtesy cars and pick-up/drop-off service',
    ],
  },
};

export default {
  locations,
  tyreServices,
  autoServices,
  tyreBrands,
  testimonials,
  faqs,
  businessStats,
  tyreReplacementGuidance,
  serviceDetails,
  companyValues,
};
